from . import sale_subscription_plan
from . import product_pricelist
from . import visar_zone
from . import product_template
from . import project_task
from . import sale_order
from . import sale_order_line
from . import account_move
from . import account_payment
