from . import test_booking_partner
from . import test_combo_offers
from . import test_partner_dedupe
from . import test_slot_hold
from . import test_wizard_flow
from . import test_agent_vocabulario
from . import test_travel_feasibility
from . import test_reschedule_capacity
from . import test_pago_factura
from . import test_lista_de_precios_default
from . import test_ruta_aviso_tarea
from . import test_mensaje_fecha_hora
from . import test_ahorro_poliza
from . import test_lista_de_precios_poliza
from . import test_cp_interes
from . import test_poliza_preagenda
from . import test_solo_exterior
from . import test_checkout_conserva_precio
from . import test_ocultar_tecnico
from . import test_extras_descripcion
from . import test_checkout_facturacion
